# Generated by Django 4.2.7 on 2024-06-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('review_text', models.TextField()),
                ('admin_approved', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(to='profiles.customerprofile')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.engineerprofile')),
            ],
        ),
    ]
