# Generated by Django 4.2.7 on 2024-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_user_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ManyToManyField(blank=True, to='profiles.customerprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
