# Generated by Django 4.2.7 on 2024-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='review_text',
        ),
    ]
